name: Coverage update
on:
  push:
    branches:
      - main
jobs:
  coverage_update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
      - name: Run test suite
        run: make test
      - name: Coverage update
        uses: OpenClassrooms/coverage-checker@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          action: update